In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [4]:
df=pd.read_csv("/content/social_media_addiction_dataset (1).csv")
df.head()

,daily_screen_time,app_opens,sleep_hours,stress_level,study_interruptions,night_usage,addiction_level
0,5.4,67,3.8,1,2,No,Moderate
1,4.3,10,6.9,2,7,No,Low
2,7.0,48,5.4,9,3,No,Moderate
3,12.0,16,6.7,2,0,No,Low
4,8.8,25,6.0,3,15,No,Moderate

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   daily_screen_time    1000 non-null   float64
 1   app_opens            1000 non-null   int64
 2   sleep_hours          1000 non-null   float64
 3   stress_level         1000 non-null   int64
 4   study_interruptions  1000 non-null   int64
 5   night_usage          1000 non-null   object
 6   addiction_level      1000 non-null   object
dtypes: float64(2), int64(3), object(2)
memory usage: 54.8+ KB

In [6]:
df.isnull().sum()

daily_screen_time      0
app_opens              0
sleep_hours            0
stress_level           0
study_interruptions    0
night_usage            0
addiction_level        0
dtype: int64

In [8]:
X = df.drop('addiction_level', axis=1)
y = df['addiction_level']

In [9]:
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
X = pd.get_dummies(X)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
y_pred = model.predict(X_test)

In [14]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.88        29
           1       0.85      0.50      0.63        22
           2       0.91      0.96      0.93       149

    accuracy                           0.90       200
   macro avg       0.87      0.79      0.81       200
weighted avg       0.90      0.90      0.89       200

In [16]:
print(confusion_matrix(y_test, y_pred))

[[ 26   0   3]
 [  0  11  11]
 [  4   2 143]]

In [17]:
import joblib
joblib.dump(model, 'multiclass_model.joblib')

['multiclass_model.joblib']